name: Test-cafe Health check
on:
  push: [master]
  #schedule:
   #- cron: "0 22 * * *"

    
 jobs:
  build:
   runs-on: ubuntu-latest
       
   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
 
      - name: Rename Directory and move
        run: mv testcafe-browser-provider-lambdatest lambdatest && cd lambdatest      
      
      - name: npm dependencies
        run: npm install
     
      - name: Install testcafe
        run: npm install -g testcafe  
      
      - name: Build Npm package
        run: npm run build
        
      - name: Link Npm
        run: npm link
        
      - name: Run single test
        name: testcafe "lambdatest:Chrome@74.0:Windows 8" "test/test.js"  
        
    
        
      
        
