name: Test-cafe Health Check
on:
  push:
    branches: [ 'master' ]

  pull_request:
    branches: [ 'master' ]

  schedule:
    - cron: "0 22 * * *" 

  workflow_dispatch:
   
jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  build:
   runs-on: ubuntu-latest
   needs: sonarqube-analysis
   env:
       LT_USERNAME: ${{ secrets.LT_USERNAME }} 
       LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
    
      
      - name: npm dependencies
        run: npm install
     
      - name: Install testcafe
        run: npm install -g testcafe  
      
      - name: Build Npm package
        run: npm run build
        
      - name: Link Npm
        run: npm link
        
      - name: Run single test
        run: testcafe "lambdatest:Chrome@74.0:Windows 8" "test/test.js"  
        
                
      - name: Run Parallel test
        run: testcafe "lambdatest:Chrome@74.0:Windows 8","lambdatest:Chrome@75.0:Windows 10" "test/test.js"
