name: Test-cafe Health Check
on:
  schedule:
  - cron: "0 22 * * *" 
  
  workflow_dispatch:
   
jobs:
  build:
   runs-on: ubuntu-latest
   env:
       LT_USERNAME: ${{ secrets.LT_USERNAME }} 
       LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
    
      
      - name: npm dependencies
        run: npm install
     
      - name: Install testcafe
        run: npm install -g testcafe  
      
      - name: Build Npm package
        run: npm run build
        
      - name: Link Npm
        run: npm link
        
      - name: Run single test
        run: testcafe "lambdatest:Chrome@74.0:Windows 8" "test/test.js"  
        
                
      - name: Run Parallel test
        run: testcafe "lambdatest:Chrome@74.0:Windows 8","lambdatest:Chrome@75.0:Windows 10" "test/test.js" 
 
         
      - name: Run Mobile test
        run: testcafe "lambdatest:Galaxy S8@9:android:isReal" "test/test.js"
      
    
        
      
        
